server:
  port: 8008

logging:
  file: ${logging.path}/p2ploan.log
  path: log
  
spring:
  datasource:
    url: jdbc:mysql://p2ploan.clv0yvzzhfdi.us-east-2.rds.amazonaws.com:3306/p2ploan?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      allow-pool-suspension: true
      auto-commit: true
      driver-class-name: com.mysql.jdbc.Driver
      connection-timeout: 20000
      idle-timeout: 10000
      maximum-pool-size: 10
      pool-name: p2ploan
      minimum-idle: 1

  jpa:
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true